**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [ ]:
## your code(for different question use different cells)
import numpy as np
a = np.array([0]*10)
print (a)


[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#Q.1.2
import numpy as np
array2 = np.array([5]*10)
print(array2)


[5 5 5 5 5 5 5 5 5 5]


In [ ]:
#Q1.3
import numpy as np
array3 = np.arange(9).reshape(3,3)
print(array3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Q1.4
import numpy as np
a = np.random.rand()
print (a)

0.7518690355558509


In [ ]:
#Q1.5
import numpy as np
array = np.linspace(0,1,20)
print (array)



[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [ ]:
#Q1.6
count = 0
word = input("enter the word: ")
for char in word.lower():
  if char in ['a','e','i','o','u']:
    count += 1
print (count)

enter the word: KhwaHIsh
2


**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [ ]:
##Q2.1
import numpy as np
numbers = np.array([12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48])
even_no = numbers[numbers%2==0]
print(even_no)


[ 12  44 102  -8  56  90 -24  48]


In [ ]:
#Q2.2
import numpy as np
array = np.random.randint(10,100,(5,4))
print(array)


[[89 56 43 29]
 [35 12 38 19]
 [17 48 19 49]
 [18 46 54 65]
 [48 53 66 17]]


In [ ]:
#Q2.3
matrix = array
array2 = matrix[0:3,0:2]
print (array2)



[[89 56]
 [35 12]
 [17 48]]


In [ ]:
#Q2.4
import numpy as np
# it will form 1D array
array_9 = np.random.randint(0,75,20)
# reshape 1D array to 2D array
array_9 = array_9.reshape(4,5)
print (array_9)



[[18 57 32 68 59]
 [13 61 28 49 14]
 [61  3 61 12 74]
 [14 43  4 39 71]]


In [ ]:
#Q2.5
# array_1 is from Q2.4
array_1 = array_9.reshape(1,20)
print (array_1)

[[18 57 32 68 59 13 61 28 49 14 61  3 61 12 74 14 43  4 39 71]]


In [ ]:
#Q2.6
import numpy as np
matrix_1 = np.random.randint(15,80,9).reshape(3,3)
matrix_2 = np.random.randint(15,80,12).reshape(3,4)

matrix_3 = matrix_1 @ matrix_2
print(matrix_3)

[[ 7667  5041  5875  3373]
 [ 7345  4508  7439  4211]
 [10390  6364 11067  6042]]


**Q.3**

(i) Check if matrix multiplication is valid

In [ ]:
#Q3(i)
# if (no. of columns of matrix_1) = (no. of rows of matrix_2)
#then matrix multiplication is valid
if matrix_1.shape[1] == matrix_2.shape[0]:
  print("matrix multiplication is valid")
else:
  print("matrix multiplication is invalid")



matrix multiplication is valid


(ii) Using loops (without using numpy)

In [ ]:
#Q3(ii)
rows_1 = len(matrix_1)
coln_1 = len(matrix_1[0])
rows_2 = len(matrix_2)
coln_2 = len(matrix_2[0])

if coln_1 != rows_2:
  print ("matrix multiplication is not valid")
else:
  result = [[0 for _ in range(coln_2)] for _ in range (rows_1)]



for i in range(rows_1):
  for j in range(coln_2):
    for k in range(coln_1):
      result[i][j] += matrix_1[i][k] * matrix_2[k][j]

print("result of matrix multiplication: ")
for row in result:
  print(row)






result of matrix multiplication: 
[np.int64(7667), np.int64(5041), np.int64(5875), np.int64(3373)]
[np.int64(7345), np.int64(4508), np.int64(7439), np.int64(4211)]
[np.int64(10390), np.int64(6364), np.int64(11067), np.int64(6042)]


**Q.4**
**Linear Regression:-** https://tahera-firdose.medium.com/linear-regression-derivation-of-slope-and-intercept-using-ordinary-least-square-971534ec6b77

(i) Given:

In [ ]:
X = [1,2,3,4,5]
Y = [2,4,5,4,5]
meanof_X = 0
for i in range(0,5):
  meanof_X = meanof_X + X[i]/5
print(meanof_X)


3.0


In [ ]:
X = [1,2,3,4,5]
Y = [2,4,5,4,5]
meanof_Y = 0
for i in range(0,5):
  meanof_Y = meanof_Y + Y[i]/5
print(meanof_Y)


4.0


In [ ]:
#slope (m)

X = [1,2,3,4,5]
Y = [2,4,5,4,5]

numerator = denominator=0

for i in range(0,5):
  numerator += (X[i]-meanof_X)*(Y[i]-meanof_Y)
  denominator += (X[i]-meanof_X)**2
m = numerator/denominator
print(m)







0.6


In [ ]:
#intercept(c)
b = meanof_Y - m*meanof_X
print (b)

2.2


Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


##  Pandas


csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).