**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [ ]:

## Q.1.
#1
import numpy as np

# 1)
zeros_arr = np.zeros(10)
print(zeros_arr)

# 2)
fives_arr = np.full(10, 5)
print(fives_arr)

# 3)
mat_3x3 = np.arange(9).reshape(3, 3)
print(mat_3x3)

# 4)
rand_num = np.random.rand()
print(rand_num)

# 5)
lin_points = np.linspace(0, 1, 20)
print(lin_points)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5 5 5 5 5 5 5 5 5 5]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
0.17064953293775453
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [1]:
##Q.1
#6
def count_vowels(s):
    vowels = "aeiouAEIOU"
    count = 0
    for ch in s:
        if ch in vowels:
            count += 1
    return count

text = input("Enter a string: ")
print("Number of vowels:", count_vowels(text))


Enter a string: apple
Number of vowels: 2


**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [2]:
import numpy as np

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

# 1)
even_numbers = numbers[0::2]
print("Even numbers by slicing:", even_numbers)

# 2)
A = np.random.randint(10, 101, size=(5, 4))
print("A:\n", A)

# 3)
subA = A[0:3, 0:2]
print("3x2 subarray:\n", subA)

# 4)
arr_1d = np.arange(20)
B = arr_1d.reshape(4, 5)
print("4x5 array B:\n", B)

# 5)
flat_B = B.flatten()
print("Flattened B:", flat_B)

# 6)
C = np.random.randint(1, 10, size=(5, 3))
product = B @ C
print("C:\n", C)
print("B @ C:\n", product)


Even numbers by slicing: [12, 44, 102, 33, 77, 121, 48]
A:
 [[17 83 53 17]
 [72 27 54 32]
 [66 10 78 62]
 [23 99 29 37]
 [36 43 99 10]]
3x2 subarray:
 [[17 83]
 [72 27]
 [66 10]]
4x5 array B:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Flattened B: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
C:
 [[9 4 7]
 [1 1 8]
 [6 8 8]
 [2 4 6]
 [1 3 6]]
B @ C:
 [[ 23  41  66]
 [118 141 241]
 [213 241 416]
 [308 341 591]]


**Q.3**

(i) Check if matrix multiplication is valid

In [3]:
#your code here# Q3(i): Check if matrix multiplication is valid
# Matrix multiplication A @ B is valid if columns of A == rows of B

def is_matrix_multiplication_valid(matrix_A, matrix_B):
    rows_A, cols_A = len(matrix_A), len(matrix_A[0])
    rows_B, cols_B = len(matrix_B), len(matrix_B[0])

    is_valid = (cols_A == rows_B)

    print(f"Matrix A shape: {rows_A} x {cols_A}")
    print(f"Matrix B shape: {rows_B} x {cols_B}")
    print(f"Valid for multiplication: {is_valid}")
    if is_valid:
        print(f"Result shape will be: {rows_A} x {cols_B}")

    return is_valid

# Test cases
A1 = [[1, 2, 3], [4, 5, 6]]  # 2x3
B1 = [[1, 2], [3, 4], [5, 6]]  # 3x2
print("Test 1:")
is_matrix_multiplication_valid(A1, B1)
print()

A2 = [[1, 2], [3, 4]]  # 2x2
B2 = [[5, 6, 7], [8, 9, 10]]  # 2x3
print("Test 2:")
is_matrix_multiplication_valid(A2, B2)
print()

A3 = [[1, 2, 3]]  # 1x3
B3 = [[1], [2]]  # 2x1 - invalid
print("Test 3:")
is_matrix_multiplication_valid(A3, B3)

Test 1:
Matrix A shape: 2 x 3
Matrix B shape: 3 x 2
Valid for multiplication: True
Result shape will be: 2 x 2

Test 2:
Matrix A shape: 2 x 2
Matrix B shape: 2 x 3
Valid for multiplication: True
Result shape will be: 2 x 3

Test 3:
Matrix A shape: 1 x 3
Matrix B shape: 2 x 1
Valid for multiplication: False


False

(ii) Using loops (without using numpy)

In [4]:
#your code here# Q3(ii): Matrix multiplication using loops (without numpy)

def matrix_multiply_loops(A, B):
    """
    Multiply two matrices A and B using nested loops
    A: m x n, B: n x p => Result: m x p
    """
    # Get dimensions
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    # Check if multiplication is valid
    if cols_A != rows_B:
        print("Error: Matrix multiplication not possible")
        return None

    # Initialize result matrix with zeros
    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

    # Perform multiplication: result[i][j] = sum of A[i][k] * B[k][j]
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]

    return result

def print_matrix(matrix, name):
    """Print matrix in readable format"""
    print(f"{name}:")
    for row in matrix:
        print([f"{val:6.1f}" for val in row])
    print()

# Test case 1: 2x3 @ 3x2 = 2x2
A1 = [[1, 2, 3], [4, 5, 6]]
B1 = [[7, 8], [9, 10], [11, 12]]
result1 = matrix_multiply_loops(A1, B1)
print("Test 1: 2x3 matrix @ 3x2 matrix")
print_matrix(A1, "Matrix A")
print_matrix(B1, "Matrix B")
if result1:
    print_matrix(result1, "Result (A @ B)")

# Test case 2: 3x2 @ 2x3 = 3x3
A2 = [[1, 2], [3, 4], [5, 6]]
B2 = [[7, 8, 9], [10, 11, 12]]
result2 = matrix_multiply_loops(A2, B2)
print("Test 2: 3x2 matrix @ 2x3 matrix")
print_matrix(A2, "Matrix A")
print_matrix(B2, "Matrix B")
if result2:
    print_matrix(result2, "Result (A @ B)")

# Test case 3: Invalid multiplication
A3 = [[1, 2, 3], [4, 5, 6]]
B3 = [[1, 2], [3, 4]]
print("Test 3: Invalid multiplication (2x3 @ 2x2)")
result3 = matrix_multiply_loops(A3, B3)

Test 1: 2x3 matrix @ 3x2 matrix
Matrix A:
['   1.0', '   2.0', '   3.0']
['   4.0', '   5.0', '   6.0']

Matrix B:
['   7.0', '   8.0']
['   9.0', '  10.0']
['  11.0', '  12.0']

Result (A @ B):
['  58.0', '  64.0']
[' 139.0', ' 154.0']

Test 2: 3x2 matrix @ 2x3 matrix
Matrix A:
['   1.0', '   2.0']
['   3.0', '   4.0']
['   5.0', '   6.0']

Matrix B:
['   7.0', '   8.0', '   9.0']
['  10.0', '  11.0', '  12.0']

Result (A @ B):
['  27.0', '  30.0', '  33.0']
['  61.0', '  68.0', '  75.0']
['  95.0', ' 106.0', ' 117.0']

Test 3: Invalid multiplication (2x3 @ 2x2)
Error: Matrix multiplication not possible


**Q.4**
**Linear Regression:-** https://tahera-firdose.medium.com/linear-regression-derivation-of-slope-and-intercept-using-ordinary-least-square-971534ec6b77

(i) Given:

In [ ]:
X = [1,2,3,4,5]
y = [2,4,5,4,5]

Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


In [5]:
# Q4: Linear Regression - Calculate slope and intercept without numpy/sklearn

X = [1, 2, 3, 4, 5]
y = [2, 4, 5, 4, 5]

# 1. Calculate mean of X
mean_X = sum(X) / len(X)
print(f"Mean of X: {mean_X}")

# 2. Calculate mean of y
mean_y = sum(y) / len(y)
print(f"Mean of y: {mean_y}")

# 3. Calculate slope (m) using formula: m = sum((xi - mean_x)(yi - mean_y)) / sum((xi - mean_x)^2)
numerator = 0
denominator = 0

for i in range(len(X)):
    numerator += (X[i] - mean_X) * (y[i] - mean_y)
    denominator += (X[i] - mean_X) ** 2

slope = numerator / denominator
print(f"Slope (m): {slope}")

# 4. Calculate intercept (c) using formula: c = mean_y - m * mean_x
intercept = mean_y - slope * mean_X
print(f"Intercept (c): {intercept}")

# 5. Calculate predicted values: y_pred = mx + c
predicted_y = []
for x_val in X:
    y_pred = slope * x_val + intercept
    predicted_y.append(y_pred)

print(f"\nPredicted values: {predicted_y}")
print(f"Actual values: {y}")

# Print regression line equation
print(f"\nLinear Regression Line: y = {slope:.4f}x + {intercept:.4f}")

Mean of X: 3.0
Mean of y: 4.0
Slope (m): 0.6
Intercept (c): 2.2

Predicted values: [2.8000000000000003, 3.4000000000000004, 4.0, 4.6, 5.2]
Actual values: [2, 4, 5, 4, 5]

Linear Regression Line: y = 0.6000x + 2.2000


##  Pandas


csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).