**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [ ]:
## your code(for different question use different cells)
##like Q.1.
#1
arr_zeros = [0]*10

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
#Q.1.2
arr_fives = [5]*10

In [ ]:
#Q.1.3
import numpy as np
arr = np.arange(9).reshape(3, 3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Q.1.4
from numpy import random
x = random.rand()

0.5524190659365037


In [ ]:
#Q.1.5
arr = [j/20 for j in range(20)]

[0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]


In [ ]:
#Q.1.6
def vowel_count(s):
    count = 0
    vowels = "aeiou"
    for char in s:
        if char.lower() in vowels:
            count += 1
    return count

5


**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [ ]:
##your code
#Q.2.1
import numpy as np
numbers_array = np.array( [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48])
def swap(arr  , i ,j):
    arr[i] , arr[j] = arr[j] , arr[i]
    return arr
l, r = 0, len(numbers_array) - 1
while(l<=r):
  if(numbers_array[r]%2==0): r-=1
  elif(numbers_array[l]%2==1): l+=1
  elif(numbers_array[r]%2==1 and numbers_array[l]%2==0):
    numbers_array = swap(numbers_array , l,r)
    l+=1
    r-=1

even_arr = numbers_array[l::]
print(even_arr)

[ -8 102  56  44  90  12 -24  48]


In [ ]:
#Q.2.2
from numpy import random
x = random.randint(90 , size = (5,4))+10
print(x)
#Q.2.3
y = x[0:3,0:2]
print(y)

[[32 40 91 82]
 [48 63 50 67]
 [45 65 63 44]
 [66 80 91 57]
 [21 40 18 44]]
[[32 40]
 [48 63]
 [45 65]]


In [ ]:
#Q.2.4
from numpy import random
x = random.randint(20 , size = 20)
print(x)
y = x.reshape(4,5)
print(y)
#Q.2.5
z  = y.reshape(20)
print(z)

[16  6  4 10 16  2  8  5  6 12  7  8 13 19 14  6 15  8  8  2]
[[16  6  4 10 16]
 [ 2  8  5  6 12]
 [ 7  8 13 19 14]
 [ 6 15  8  8  2]]
[16  6  4 10 16  2  8  5  6 12  7  8 13 19 14  6 15  8  8  2]


**Q.3**

(i) Check if matrix multiplication is valid

In [ ]:
#your code here
def is_Mat_Mult_Valid(A , B):
   arr1 = np.array(A)
   arr2 = np.array(B)
   if arr1.shape[1]==arr2.shape[0]:
    print("VALID")
   else:
    print("INVALID")


(ii) Using loops (without using numpy)

In [ ]:
#your code here
def Mat_Mult(A , B):
  arr1 = np.array(A)
  arr2 = np.array(B)
  rows_A, cols_A = arr1.shape
  rows_B, cols_B = arr2.shape
  result = np.zeros((rows_A, cols_B))
  for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += arr1[i][k] * arr2[k][j]

  return result

**Q.4**
(i) Given:

In [ ]:
X = [1,2,3,4,5]
Y = [2,4,5,4,5]

total_x = 0
for i in range(len(X)):
    total_x+=X[i]
mean_x = total_x/len(X)
print(mean_x)

total_y = 0
for i in range(len(Y)):
    total_y+=Y[i]
mean_y = total_y/len(Y)
print(mean_y)

num_sum = 0
den_sum = 0
for i in range(len(X)):
    num_sum += (X[i]-mean_x)*(Y[i]-mean_y)
    den_sum += (X[i]-mean_x)*(X[i]-mean_x)
m = num_sum/den_sum
print(m)
c = mean_y - m*mean_x
print(c)


3.0
4.0
0.6
2.2


Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


##  Pandas


csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).

In [ ]:

import pandas as pd

url = "https://drive.google.com/uc?export=download&id=1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq"

df = pd.read_csv(url)
#print(df)
#print(df.fillna({"internet_access": df["internet_access"].mean()}))
#print(df.iloc[[0,5],0:20])






   hours_studied  attendance_percent  parent_education  internet_access  \
0       4.743108           79.781453               3.0              NaN   
5      12.954310           66.696510               3.0              0.0   

   school_type  sports_participation  part_time_job  siblings  \
0          NaN                   1.0            0.0       4.0   
5          1.0                   3.0            1.0       1.0   

   commute_time_mins  favorite_subject  club_member  self_study_hours  \
0          31.681382               2.0          0.0          1.230251   
5          37.296292               0.0          1.0          1.346733   

   pet_count  locker_number  bus_route  screen_time_weekly   height_cm  \
0        0.0          169.0        2.0            2.339672  157.398274   
5        1.0          584.0       18.0           14.535370  176.745495   

   weight_kg  lunch_type  math_tutor  
0  53.055261         0.0         NaN  
5  64.342675         2.0         1.0  
