**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [ ]:
## your code(for different question use different cells)
##like Q.1.1
#1
import numpy as np
a1=np.array([0]*10)
print(a1)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#Q.1.2
import numpy as np
a2=np.array([5]*10)
print(a2)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
#Q.1.3.
import numpy as np
a3=np.random.randint(9,size=(3,3))
print(a3)

[[7 6 1]
 [4 5 8]
 [6 8 6]]


In [ ]:
#Q.1.4
import numpy as np
x=np.random.rand()
print(x)

0.5490530775678774


In [ ]:
#Q.1.5.
import numpy as np
a4=np.linspace(0,1,20,endpoint=False)
print(a4)

[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95]


In [ ]:
s=input("enter string")
v=0
for i in s:
  if i in ['a','e','i','o','u','A','E','I','O','U']:
    v+=1;
print(v)


enter stringHi I am Nandana
6


**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [ ]:
##Q.2.1.
import numpy as np
a5=np.array([12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48])
even=a5[a5%2==0]
print(even)

[ 12  44 102  -8  56  90 -24  48]


In [ ]:
#Q.2.2
import numpy as np
a6=np.random.randint(10,100,(5,4))
print(a6)

[[48 74 25 28]
 [48 80 21 91]
 [75 22 68 67]
 [47 21 64 41]
 [95 89 72 69]]


In [ ]:
#Q.2.3
import numpy as np
a7=a6[0:3,0:2]
print(a7)

[[48 74]
 [48 80]
 [75 22]]


In [ ]:
#Q.2.4
import numpy as np
a=np.random.randint(0,100,size=20)
a8=a.reshape(4,5)
print(a8)

[[63 65 28  1 22]
 [63 49 46 20 20]
 [55  2 58 82 75]
 [97 49 58 45 57]]


In [ ]:
#Q2.5.
import numpy as np
a9=a8.reshape(20)
print(a9)

[63 65 28  1 22 63 49 46 20 20 55  2 58 82 75 97 49 58 45 57]


In [ ]:
#Q.2.6
import numpy as np
m1=np.random.randint(0,100,9).reshape(3,3)
m2=np.random.randint(0,100,12).reshape(3,4)
m3=np.array([0]*12).reshape(3,4)
for i in range(0,3):
  for j in range(0,4):
    for k in range(0,3):
      m3[i][j]=m3[i][k]+m1[i][k]*m2[k][j]
print(m1)
print(m2)
print(m3)

[[ 4 90 73]
 [71 38 70]
 [16 95  4]]
[[49 63 81 99]
 [91 51  8 10]
 [97 30 31 59]]
[[7081 2190 5173 9480]
 [6790 2100 4574 8704]
 [ 388  120 1004 1240]]


**Q.3**

(i) Check if matrix multiplication is valid

In [ ]:
#your code here
import numpy as np
r1,c1=m1.shape
r2,c2=m2.shape
if(c1==r2):
  print("valid")
else:
  print("not valid")

valid


(ii) Using loops (without using numpy)

In [ ]:
#your code here
c1=0
r2=0
c2=0
for i in m1[0]:
  c1+=1
for j in m2[0]:
  c2+=1
i=0
for k in m2:
  r2+=1
if(r2==c1):
  print("valid")
else:
  print("invalid")
#print(c1,c2,r2)

valid


**Q.4**
**Linear Regression:-** https://tahera-firdose.medium.com/linear-regression-derivation-of-slope-and-intercept-using-ordinary-least-square-971534ec6b77

(i) Given:

In [ ]:
X = [1,2,3,4,5]
y = [2,4,5,4,5]

Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


In [ ]:
X=[1,2,3,4,5]
sum=0
for i in X:
  sum+=i
meanx=sum/len(X)
print(meanx)

3.0


In [ ]:
Y=[2,4,5,4,5]
sum=0
for i in Y:
  sum+=i
meany=sum/len(Y)
print(meany)

4.0


In [ ]:
num=0
den=0
for i in range(len(X)):
  num+=(X[i]-meanx)*(Y[i]-meany)
  den+=(X[i]-meanx)*(X[i]-meanx)
m=num/den
print(m)

0.6


In [ ]:
print(meany-m*meanx)

2.2


##  Pandas


csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).

In [4]:
pip install pandas


   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ------------- -------------------------- 3.7/11.0 MB 20.7 MB/s eta 0:00:01
   ---------------------- ----------------- 6.3/11.0 MB 16.4 MB/s eta 0:00:01
   --------------------------------- ------ 9.2/11.0 MB 15.1 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 14.2 MB/s  0:00:00
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   --------- ------------------------------ 2.9/12.8 MB 16.1 MB/s eta 0:00:01
   ------------------ --------------------- 6.0/12.8 MB 13.9 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.8 MB 13.6 MB/s eta 0:00:01
   ----------------------------------- ---- 11.3/12.8 MB 13.4 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 12.9 MB/s  0:00:00

   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------- ----------------------------- 1/4 [t

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import pandas as pd
df=pd.read_csv('performance_dataset.csv')

In [6]:
print(df.head(10))
print(df.tail(10))
print(f"Shape: {df.shape}")

   hours_studied  attendance_percent  parent_education  internet_access  \
0       4.743108           79.781453               3.0              NaN   
1      10.992036           97.666558               3.0              1.0   
2       8.848935           57.950598               2.0              0.0   
3       3.481116           84.636899               0.0              0.0   
4       6.264199           58.081774               1.0              0.0   
5      12.954310           66.696510               3.0              0.0   
6       0.719962           60.457167               2.0              0.0   
7       6.713262           63.990601               1.0              1.0   
8      11.797809           84.437431               3.0              1.0   
9       5.399779           76.552077               2.0              0.0   

   school_type  sports_participation  part_time_job  siblings  \
0          NaN                   1.0            0.0       4.0   
1          0.0                   3.0        

In [7]:
print(df.loc[0])

hours_studied             4.743108
attendance_percent       79.781453
parent_education          3.000000
internet_access                NaN
school_type                    NaN
sports_participation      1.000000
part_time_job             0.000000
siblings                  4.000000
commute_time_mins        31.681382
favorite_subject          2.000000
club_member               0.000000
self_study_hours          1.230251
pet_count                 0.000000
locker_number           169.000000
bus_route                 2.000000
screen_time_weekly        2.339672
height_cm               157.398274
weight_kg                53.055261
lunch_type                0.000000
math_tutor                     NaN
reading_habit             1.000000
video_game_freq           0.000000
music_hours_weekly        0.898032
parent_meeting_freq       1.000000
uniform                   1.000000
Name: 0, dtype: float64


In [8]:
print(df.loc[[0, 24]])

    hours_studied  attendance_percent  parent_education  internet_access  \
0        4.743108           79.781453               3.0              NaN   
24       4.238358           98.871022               0.0              1.0   

    school_type  sports_participation  part_time_job  siblings  \
0           NaN                   1.0            0.0       4.0   
24          1.0                   2.0            0.0       NaN   

    commute_time_mins  favorite_subject  ...  screen_time_weekly   height_cm  \
0           31.681382               2.0  ...            2.339672  157.398274   
24          36.130234               3.0  ...            9.982128  146.562995   

    weight_kg  lunch_type  math_tutor  reading_habit  video_game_freq  \
0   53.055261         0.0         NaN            1.0              0.0   
24  60.977466         0.0         NaN            0.0              0.0   

    music_hours_weekly  parent_meeting_freq  uniform  
0             0.898032                  1.0      1.0  
2

In [9]:
print(pd.options.display.max_rows) 

60


In [10]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   hours_studied         4750 non-null   float64
 1   attendance_percent    4750 non-null   float64
 2   parent_education      4750 non-null   float64
 3   internet_access       4750 non-null   float64
 4   school_type           4750 non-null   float64
 5   sports_participation  4750 non-null   float64
 6   part_time_job         4750 non-null   float64
 7   siblings              4750 non-null   float64
 8   commute_time_mins     4750 non-null   float64
 9   favorite_subject      4750 non-null   float64
 10  club_member           4750 non-null   float64
 11  self_study_hours      4750 non-null   float64
 12  pet_count             4750 non-null   float64
 13  locker_number         4750 non-null   float64
 14  bus_route             4750 non-null   float64
 15  screen_time_weekly   

In [13]:
df=df.rename(columns={'screen_time_weekly':'weekly_screentime'})
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   hours_studied         4750 non-null   float64
 1   attendance_percent    4750 non-null   float64
 2   parent_education      4750 non-null   float64
 3   internet_access       4750 non-null   float64
 4   school_type           4750 non-null   float64
 5   sports_participation  4750 non-null   float64
 6   part_time_job         4750 non-null   float64
 7   siblings              4750 non-null   float64
 8   commute_time_mins     4750 non-null   float64
 9   favorite_subject      4750 non-null   float64
 10  club_member           4750 non-null   float64
 11  self_study_hours      4750 non-null   float64
 12  pet_count             4750 non-null   float64
 13  locker_number         4750 non-null   float64
 14  bus_route             4750 non-null   float64
 15  weekly_screentime    

In [21]:
print(df.iloc[5:10,2:6])# 5th to 9th row and 2nd to 5th column
print(df.iloc[0])

    parent_education  internet_access  school_type  sports_participation
7                1.0              1.0          2.0                   2.0
8                3.0              1.0          0.0                   1.0
9                2.0              0.0          1.0                   2.0
10               0.0              1.0          0.0                   3.0
11               0.0              0.0          1.0                   0.0
hours_studied             8.848935
attendance_percent       57.950598
parent_education          2.000000
internet_access           0.000000
school_type               0.000000
sports_participation      1.000000
part_time_job             0.000000
siblings                  3.000000
commute_time_mins        28.859972
favorite_subject          0.000000
club_member               1.000000
self_study_hours          0.233440
pet_count                 0.000000
locker_number           183.000000
bus_route                 1.000000
weekly_screentime        16.989369
he

In [16]:
print(df.isnull().sum().sum())
df.fillna(0,inplace=True)

6250


In [31]:
df = pd.read_csv('performance_dataset.csv')
df.drop(0, inplace=True)
df.head(2)



hours_studied  attendance_percent  parent_education  internet_access  \
1      10.992036           97.666558               3.0              1.0   
2       8.848935           57.950598               2.0              0.0   

   school_type  sports_participation  part_time_job  siblings  \
1          0.0                   3.0            NaN       1.0   
2          0.0                   1.0            0.0       3.0   

   commute_time_mins  favorite_subject  ...  screen_time_weekly   height_cm  \
1          19.423883               4.0  ...                 NaN  151.295654   
2          28.859972               0.0  ...           16.989369  183.900640   

   weight_kg  lunch_type  math_tutor  reading_habit  video_game_freq  \
1  60.628213         2.0         1.0            1.0              3.0   
2  65.655529         0.0         1.0            0.0              1.0   

   music_hours_weekly  parent_meeting_freq  uniform  
1            3.291397                  0.0      0.0  
2            0.000000                  2.0      1.0  

[2 rows x 25 columns]

In [33]:
df = pd.read_csv('performance_dataset.csv')
df=df.drop('hours_studied',axis=1)
print(df.head(1))

   attendance_percent  parent_education  internet_access  school_type  \
0           79.781453               3.0              NaN          NaN   

   sports_participation  part_time_job  siblings  commute_time_mins  \
0                   1.0            0.0       4.0          31.681382   

   favorite_subject  club_member  ...  screen_time_weekly   height_cm  \
0               2.0          0.0  ...            2.339672  157.398274   

   weight_kg  lunch_type  math_tutor  reading_habit  video_game_freq  \
0  53.055261         0.0         NaN            1.0              0.0   

   music_hours_weekly  parent_meeting_freq  uniform  
0            0.898032                  1.0      1.0  

[1 rows x 24 columns]


In [34]:
fildf=df[df['siblings']>2]
print(fildf)

      attendance_percent  parent_education  internet_access  school_type  \
0              79.781453               3.0              NaN          NaN   
2              57.950598               2.0              0.0          0.0   
3              84.636899               0.0              0.0          0.0   
7              63.990601               1.0              1.0          2.0   
9              76.552077               2.0              0.0          1.0   
...                  ...               ...              ...          ...   
4983           97.183643               1.0              1.0          2.0   
4984           68.998939               3.0              1.0          2.0   
4987           73.310643               3.0              1.0          0.0   
4995           66.031236               0.0              1.0          2.0   
4999           89.559193               2.0              0.0          0.0   

      sports_participation  part_time_job  siblings  commute_time_mins  \
0            

In [35]:
df = pd.read_csv('performance_dataset.csv')
df['total_study_hours']=df['hours_studied']+df['self_study_hours']
print(df.head(2))

   hours_studied  attendance_percent  parent_education  internet_access  \
0       4.743108           79.781453               3.0              NaN   
1      10.992036           97.666558               3.0              1.0   

   school_type  sports_participation  part_time_job  siblings  \
0          NaN                   1.0            0.0       4.0   
1          0.0                   3.0            NaN       1.0   

   commute_time_mins  favorite_subject  ...   height_cm  weight_kg  \
0          31.681382               2.0  ...  157.398274  53.055261   
1          19.423883               4.0  ...  151.295654  60.628213   

   lunch_type  math_tutor  reading_habit  video_game_freq  music_hours_weekly  \
0         0.0         NaN            1.0              0.0            0.898032   
1         2.0         1.0            1.0              3.0            3.291397   

   parent_meeting_freq  uniform  total_study_hours  
0                  1.0      1.0           5.973359  
1                