**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [ ]:
##QUES1....Array of 10 zeros
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

##QUES2....Array of 10 fives
import numpy as np
five_array=np.ones(10)
five_array1=np.ones(10)*5
print("An array of 10 fives:")
print(five_array1)

##QUES3....3x3 matrix with values ranging from 0 to 8
import numpy as np
random =  np.arange(0, 9).reshape(3,3)
print(random)

##QUES4....Random Number
from numpy import random
y=random.rand()
print(y)

##QUES5....Array of 2D LINEARLY SPACED POINTS BETWEEN 0 AND 1
import numpy as np
lsarray=np.linspace(0,1,20)
print(lsarray)

##QUES6....Count vowels in a string
str=input("Enter a string:")
vowels=0
for i in str:
      if(i=='a' or i=='e' or i=='i' or i=='o' or i=='u' or i=='A' or i=='E' or i=='I' or i=='O' or i=='U'):
            vowels=vowels+1
print("Number of vowels are:")
print(vowels)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
0.4189977115420118
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
Enter a string:tereef
Number of vowels are:
3


**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [ ]:
##QUES1
my_array=[12,7,44,19,102,-8,33,56,77,90,121,-24,48]
even=[n for n in my_array if n%2==0]
print(even)

[12, 44, 102, -8, 56, 90, -24, 48]


In [ ]:
##QUES2
import numpy as np
array2=np.random.randint(10,100,size=(5,4))
print("2d array as specified is :")
print(array2)

2d array as specified is :
[[55 67 80 88]
 [15 41 61 88]
 [75 43 72 57]
 [18 63 53 97]
 [92 52 36 12]]


In [ ]:
#QUES3
#using slicing method
subarray=array2[:3,:2]
print("The extracted subarray:")
print(subarray)

The eextracted subarray:
[[55 67]
 [15 41]
 [75 43]]


In [ ]:
##QUES4
array1d=np.arange(1,21)
array45=array1d.reshape(4,5)
print("The original array is:")
print(array1d)
print("The 4x5 array is:")
print(array45)

The original array is:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
The 4x5 array is:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
##QUES5 Flatten the array
flatarray=array45.flatten()
print("The flattened array is:")
print(flatarray)

The flattened array is:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
##QUES6
##one array from prev ques
array2=np.random.randint(10,100,size=(5,4))##from ques2
A=array2
B=np.random.randint(1,10,size=(4,2))
product=A@B
print("The product of the two arrays is:")
print(product)

The product of the two arrays is:
[[ 942 1540]
 [ 425 1084]
 [1284 1694]
 [ 975 1622]
 [ 264  344]]


**Q.3**

(i) Check if matrix multiplication is valid

In [ ]:
#your code here

(ii) Using loops (without using numpy)

In [ ]:
#your code here

**Q.4**
**Linear Regression:-** https://tahera-firdose.medium.com/linear-regression-derivation-of-slope-and-intercept-using-ordinary-least-square-971534ec6b77

(i) Given:

In [ ]:
##mean of x
sum=0
X=[1,2,3,4,5]
b=len(X)
for n in X:
  sum=sum+n
meanofx=sum/b
print(meanofx)

3.0


In [ ]:
##mean of y
sum1=0
Y=[2,4,5,4,5]
a=len(Y)
for n in Y:
  sum1=sum1+n
meanofy=sum1/a
print(meanofy)

4.0


In [ ]:
##slope of the data
X=[1,2,3,4,5]
Y=[2,4,5,4,5]
n=0
d=0
for i in range(len(X)):
  n=n+((X[i]-meanofx)*(Y[i]-meanofy))
for j in range(len(X)):
  d=d+((X[j]-meanofx)**2)
slope=n/d
print("The slope is:",slope)

The slope is: 0.6


In [ ]:
##y intercept
c=meanofy-(slope*meanofx)
print("The y intercept is:",c)

The y intercept is: 2.2


In [ ]:
X = [1,2,3,4,5]
y = [2,4,5,4,5]

Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


##  Pandas


In [12]:
import pandas as pd
df=pd.read_csv('performance_dataset.csv')


In [13]:
df.head(7)

hours_studied  attendance_percent  parent_education  internet_access  \
0       4.743108           79.781453               3.0              NaN   
1      10.992036           97.666558               3.0              1.0   
2       8.848935           57.950598               2.0              0.0   
3       3.481116           84.636899               0.0              0.0   
4       6.264199           58.081774               1.0              0.0   
5      12.954310           66.696510               3.0              0.0   
6       0.719962           60.457167               2.0              0.0   

   school_type  sports_participation  part_time_job  siblings  \
0          NaN                   1.0            0.0       4.0   
1          0.0                   3.0            NaN       1.0   
2          0.0                   1.0            0.0       3.0   
3          0.0                   2.0            0.0       4.0   
4          0.0                   3.0            1.0       2.0   
5          1.0                   3.0            1.0       1.0   
6          NaN                   0.0            1.0       0.0   

   commute_time_mins  favorite_subject  ...  screen_time_weekly   height_cm  \
0          31.681382               2.0  ...            2.339672  157.398274   
1          19.423883               4.0  ...                 NaN  151.295654   
2          28.859972               0.0  ...           16.989369  183.900640   
3          40.083853               1.0  ...           11.631093  164.835570   
4          23.838820               2.0  ...           15.372885  166.303604   
5          37.296292               0.0  ...           14.535370  176.745495   
6                NaN               4.0  ...            7.893048  146.213152   

   weight_kg  lunch_type  math_tutor  reading_habit  video_game_freq  \
0  53.055261         0.0         NaN            1.0              0.0   
1  60.628213         2.0         1.0            1.0              3.0   
2  65.655529         0.0         1.0            0.0              1.0   
3  38.357323         2.0         1.0            2.0              1.0   
4  39.271753         NaN         0.0            1.0              2.0   
5  64.342675         2.0         1.0            2.0              2.0   
6  68.420398         2.0         1.0            3.0              1.0   

   music_hours_weekly  parent_meeting_freq  uniform  
0            0.898032                  1.0      1.0  
1            3.291397                  0.0      0.0  
2            0.000000                  2.0      1.0  
3            2.410233                  0.0      0.0  
4            1.200275                  1.0      1.0  
5            6.485664                  2.0      NaN  
6            7.476785                  0.0      0.0  

[7 rows x 25 columns]

In [14]:
#rename a column
df=df.rename(columns={'school_type':'typeofschool'})
df.head()

hours_studied  attendance_percent  parent_education  internet_access  \
0       4.743108           79.781453               3.0              NaN   
1      10.992036           97.666558               3.0              1.0   
2       8.848935           57.950598               2.0              0.0   
3       3.481116           84.636899               0.0              0.0   
4       6.264199           58.081774               1.0              0.0   

   typeofschool  sports_participation  part_time_job  siblings  \
0           NaN                   1.0            0.0       4.0   
1           0.0                   3.0            NaN       1.0   
2           0.0                   1.0            0.0       3.0   
3           0.0                   2.0            0.0       4.0   
4           0.0                   3.0            1.0       2.0   

   commute_time_mins  favorite_subject  ...  screen_time_weekly   height_cm  \
0          31.681382               2.0  ...            2.339672  157.398274   
1          19.423883               4.0  ...                 NaN  151.295654   
2          28.859972               0.0  ...           16.989369  183.900640   
3          40.083853               1.0  ...           11.631093  164.835570   
4          23.838820               2.0  ...           15.372885  166.303604   

   weight_kg  lunch_type  math_tutor  reading_habit  video_game_freq  \
0  53.055261         0.0         NaN            1.0              0.0   
1  60.628213         2.0         1.0            1.0              3.0   
2  65.655529         0.0         1.0            0.0              1.0   
3  38.357323         2.0         1.0            2.0              1.0   
4  39.271753         NaN         0.0            1.0              2.0   

   music_hours_weekly  parent_meeting_freq  uniform  
0            0.898032                  1.0      1.0  
1            3.291397                  0.0      0.0  
2            0.000000                  2.0      1.0  
3            2.410233                  0.0      0.0  
4            1.200275                  1.0      1.0  

[5 rows x 25 columns]

In [15]:
#4 slicing type
print(df.iloc[0:11])
#prints rows 0 to 10 , 11 excluded

    hours_studied  attendance_percent  parent_education  internet_access  \
0        4.743108           79.781453               3.0              NaN   
1       10.992036           97.666558               3.0              1.0   
2        8.848935           57.950598               2.0              0.0   
3        3.481116           84.636899               0.0              0.0   
4        6.264199           58.081774               1.0              0.0   
5       12.954310           66.696510               3.0              0.0   
6        0.719962           60.457167               2.0              0.0   
7        6.713262           63.990601               1.0              1.0   
8       11.797809           84.437431               3.0              1.0   
9        5.399779           76.552077               2.0              0.0   
10       5.963342           54.191108               0.0              1.0   

    typeofschool  sports_participation  part_time_job  siblings  \
0            NaN    

In [ ]:
#5
df=df.fillna('-',inplace=Yes)
df.head()

In [ ]:
#6
df=df.drop(columns=["hours_studied"])

In [ ]:
#7
df=df.filter(regex='p')


In [ ]:
#8
df=pd.read_csv('performance_dataset.csv')
df["totalhrs"]=df.hours_studied + df.self_study_hours
df.head()